### ISSUE TITLE
关于博客里面包蟹的作用和必要性

### ISSUE THREAD

**Issue by jasminecjc** [que01/dva-demo#1]
你好，我看到你博客里写的关于面包屑那里有些没弄明白，我现在已经初步完成路由点击左侧区域右侧区域变化，不太理解面包屑的作用和必要性，麻烦解答下

**Comment by que01** [comment]
你好，面包屑的必要性这个没有必要做讨论 ，如果你的产品不需要 那么可以不要。这里做面包屑，是为了实践组件之间的通讯。这个在任何产品内部无法避免
