### ISSUE TITLE
怎么跑项目呢？

### ISSUE THREAD

**Issue by 290068483** [que01/dva-demo#3]
npm run start 后，就提示打开了8989监听端口，你的页面呢？怎么看效果呢，为什么你的文章里面没有写

**Comment by 290068483** [comment]
我clone你的项目也是一样的哦

**Comment by que01** [comment]
@290068483 。。。真的很抱歉疏于管理我到今天才看到，因为这个项目比较老了所以维护不是很多，issue我也很少看。
虽然99%你已经不需要这个答案但是我还是回复一下可能无法运行的原因，因为代码版本，真的有些老了新出的包可能会导致配合上的兼容问题。
不过我今天自己使用yarn跑了一下 没出现问题。。。
